Articles are displayed by category
CraftAcademy/newsroom-april pull request #10
Opened 2018-05-25 18:19 UTC by alghazu

### Articles are displayed by category
### PT Link: https://www.pivotaltracker.com/story/show/157771224

### What we did: 
- Add category model and controller
- Create relation between category and article models
- Create a nav bar for articles
- Create a drop down menu for categories when creating new article
- Modify previous tests including article creation to include category attribute

2018-05-25 18:33 UTC, alghazu commented
We did, there is a feature file created in first commit `c90bcd2`

2018-05-25 20:36 UTC, ghost approved these changes
Looks good to me

2018-05-26 07:33 UTC, alghazu commented
@tochman There are specs for category.
https://github.com/CraftAcademy/newsroom-april/pull/10/files#diff-2dd1d3edb24becaa29be930973f468e5

2018-05-26 20:23 UTC, tochman requested changes
Please make sure that your feature file names reflect what the feature is about. `create_article_form.feature` and `article_categories.feature` feels weird.

2018-05-26 20:23 UTC, tochman commented on app/views/articles/index.html.haml
> +  - Category.all.each do |category|
Please avoid calling models from a view. Set that in the controller. `@categories = Category.all`

2018-05-26 20:23 UTC, tochman commented on app/views/articles/new.html.haml
> +  = form.collection_select :category_id, Category.all, :id, :name
Please avoid calling models from a view. Set that in the controller or a helper. `@categories = Category.all`

2018-05-26 20:23 UTC, tochman commented on config/routes.rb
> +  resources :categories, only: [:show]
When do you use the `show` route?

2018-05-26 20:23 UTC, tochman commented on spec/models/article_spec.rb
> +    it { is_expected.to belong_to :category}
In what way is this a validation test?

2018-05-26 20:23 UTC, tochman commented on spec/models/category_spec.rb
> +      expect(category).to be_valid
Please take a look at the other model specs and factory tests. Check for consistency. Are you following the same format throughout the project?

2018-05-27 14:07 UTC, alghazu commented on app/views/articles/index.html.haml
> +  - Category.all.each do |category|
:+1:

2018-05-27 14:07 UTC, alghazu commented on app/views/articles/new.html.haml
> +  = form.collection_select :category_id, Category.all, :id, :name
:+1:

2018-05-27 14:14 UTC, alghazu commented on config/routes.rb
> +  resources :categories, only: [:show]
When a category is clicked from categories-bar, it links to the category-show route, which displays all the articles in that category on index page.
Should we use a different route, e.g. call it (filter) or so?

2018-05-27 14:17 UTC, alghazu commented on spec/models/article_spec.rb
> +    it { is_expected.to belong_to :category}
:+1:

2018-05-27 14:17 UTC, alghazu commented on spec/models/category_spec.rb
> +      expect(category).to be_valid
:+1:

2018-05-27 15:05 UTC, alghazu commented
All comments addressed, and solved merge conflicts

2018-05-27 16:02 UTC, merged