Edit articles
CraftAcademy/newsroom-april pull request #11
Opened 2018-05-26 11:14 UTC by koggs

###  Journalist can edit articles
### PT Link https://www.pivotaltracker.com/story/show/157887097

### What we did:
- Create edit view with a form
- Create link to edit article in show view
- Modify article controller

2018-05-26 11:24 UTC, GeorgeJLewis approved these changes
Looks good to me

2018-05-26 12:29 UTC, magnus-thor requested changes

2018-05-26 12:29 UTC, magnus-thor commented on app/views/articles/edit.html.haml
> +  = form.submit 'Save Article'
You have this same form on new.html.haml, extract the forms to a partial and render the partial on each page

2018-05-26 12:29 UTC, magnus-thor commented on features/edit_articles.feature
> +  Scenario: Journalist leaves headline empty
Indentation is off

2018-05-26 12:29 UTC, magnus-thor commented on features/edit_articles.feature
> +  Scenario: Journalist leaves content empty
Indentation is off

2018-05-26 21:38 UTC, alghazu commented
@magnus-thor Addressed comments

2018-05-26 21:47 UTC, alghazu commented
@magnus-thor solved merge conflicts

2018-05-27 12:00 UTC, magnus-thor approved these changes
Looks good

2018-05-27 12:00 UTC, merged