User can change language
CraftAcademy/newsroom-april pull request #14
Opened 2018-05-29 13:40 UTC by koggs

### User can change application language  (SE and EN)
### PT Link: https://www.pivotaltracker.com/story/show/157771300

### What we did:
- Add locales to application
- Add se.yml and se.devise.yml
- Add rails i18 gem
- Add set locale method in application controller

2018-05-30 00:31 UTC, alghazu requested changes

2018-05-30 00:31 UTC, alghazu commented on app/views/articles/show.html.haml
>    = form.submit
submit button missing translation

2018-05-30 09:05 UTC, koggs commented on app/views/articles/show.html.haml
>    = form.submit
amongst other things but it's fixed :)

2018-05-30 09:31 UTC, alghazu approved these changes
:+1:

2018-05-30 11:30 UTC, tochman commented on app/views/layouts/_navbar.html.haml
> +  = link_to "Svenska", { locale: 'sv' }
Why don't you use locales for "English" and "Svenska"?  ;-)

2018-05-30 12:55 UTC, koggs commented
@tochman  
Addressed comment

2018-05-31 10:12 UTC, tochman approved these changes
👍

2018-05-31 10:12 UTC, merged