Add coveralls gem for test coverage metrics
CraftAcademy/newsroom-april pull request #4
Opened 2018-05-22 20:27 UTC by koggs

### Test Coverage Metrics

### PT Link https://www.pivotaltracker.com/story/show/157736555

### What we did:
- Set up Coveralls for test coverage
- Configure Coveralls for Rspec and Cucumber

2018-05-22 21:00 UTC, alghazu requested changes

2018-05-22 21:00 UTC, alghazu commented on features/support/env.rb
> +Coveralls.wear_merged!
I think should be:
`Coveralls.wear_merged!('rails')`

2018-05-22 21:00 UTC, alghazu commented on spec/spec_helper.rb
> +Coveralls.wear_merged!
I think should be:
`Coveralls.wear_merged!('rails')`

2018-05-23 11:39 UTC, koggs commented on spec/spec_helper.rb
> +Coveralls.wear_merged!
I fixed it

2018-05-23 13:25 UTC, faraznaeem requested changes

2018-05-23 13:25 UTC, faraznaeem commented on spec/spec_helper.rb
> +
This code should be in the rails helper

2018-05-23 13:25 UTC, faraznaeem commented on coverage/.resultset.json
> +{
This file should be removed from version control

2018-05-23 13:25 UTC, faraznaeem commented on coverage/.last_run.json
> +}
this file should be removed from version control

2018-05-23 13:51 UTC, koggs commented on coverage/.last_run.json
> +}
Comments have been addressed

2018-05-23 14:01 UTC, alghazu commented
Done

2018-05-24 06:45 UTC, faraznaeem approved these changes

2018-05-24 07:17 UTC, alghazu approved these changes

2018-05-24 07:23 UTC, GeorgeJLewis approved these changes

2018-05-24 07:23 UTC, GeorgeJLewis commented
LGTM

2018-05-24 07:25 UTC, merged